site_name: Sky Games Restored
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: pink
  favicon: assets/icon.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - header.autohide
extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://denki.co.uk/sky/Discord.png
    - icon: fontawesome/brands/github
      link: https://github.com/cobaltgit/skygames-restored
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg